version: "3.7"
services:
  app:
    container_name: espial
    image: "${IMAGE_NAME}:${IMAGE_TAG}"
    environment:
      - SQLITE_DATABASE
      - IP_FROM_HEADER
      - ekg_datadir
    ports:
      - "${LISTEN_ADDRESS}:${LISTEN_PORT}:3000"
    volumes:
      - "data:/app/data"
volumes:
  data:
    name: "${VOLUME_NAME}"